name: pitpc_app
description: AplicaciÃ³n Flutter para PITPC que consume el backend existente.
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: '>=3.24.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0

flutter:
  uses-material-design: true
